Repository caolan/async, pull requests merged in 2018-07, with the labels that each got.

#1542 feat: Canceling flows
  intro.md
  lib/auto.js
  lib/doDuring.js
  lib/doWhilst.js
  lib/during.js
  lib/eachOf.js
  lib/forever.js
  lib/internal/eachOfLimit.js
  lib/retry.js
  lib/tryEach.js
  lib/waterfall.js
  lib/whilst.js
  test/auto.js
  test/during.js
  test/eachOf.js
  test/forever.js
  test/parallel.js
  test/retry.js
  test/until.js
  test/waterfall.js
  test/whilst.js
Labels: feature

#1556 feat: Iterable queues
  lib/internal/DoublyLinkedList.js
  lib/internal/queue.js
  lib/queue.js
  test/queue.js
Labels: feature, queue

#1558 Add limit value to `mapLimit` example
  intro.md
Labels: docs

#1557 breaking: remove during, make test functions in until/whilst async
  lib/doDuring.js
  lib/doUntil.js
  lib/doWhilst.js
  lib/during.js
  lib/index.js
  lib/until.js
  lib/whilst.js
  support/aliases.txt
  test/during.js
  test/es2017/asyncFunctions.js
  test/until.js
  test/whilst.js
Labels: breaking-change
